
// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/config/environment';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the Supabase client only if credentials are provided
// This allows the app to run without Supabase for the static employer directory
let supabaseClient: SupabaseClient<Database> | null = null;

if (SUPABASE_URL && SUPABASE_ANON_KEY && !SUPABASE_URL.includes('your-project-id')) {
  supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      autoRefreshToken: true,
      persistSession: true
    }
  });

  // For development debugging
  if (import.meta.env.MODE === 'development') {
    console.log('🔌 Supabase client initialized with URL:', SUPABASE_URL);
  }
} else {
  console.log('⚠️ Supabase not configured - running in static mode (employer directory only)');
}

export const supabase = supabaseClient;
